LP-81: Добавить ещё одно WEB API (кроме Canvas, Fetch)
LastPracticant/ya-practicum-m2 pull request #100
Opened 2021-03-24 10:52 UTC by AirMust

2021-03-25 08:37 UTC, webtreegroup commented on server/routing/index.ts
> +export * from './Routing';
тут все-таки нужно `routing`

2021-03-25 08:37 UTC, webtreegroup commented on client/core/components/GameCanvas/GameCanvas.tsx
> +    const fullScreenHandle = useCallback(() => {
fullScreenHandle -> handleSetFullScreen, обработчики принято писать либо с префиксом `handle`, например `handleClick`, либо с постфиксом `handler`, например `clickHandler`, но все же лучше первый вариант, т.к. больше соответствует по духу нашему проекту.

2021-03-25 08:37 UTC, webtreegroup commented on client/core/components/GameCanvas/GameCanvas.tsx
> +    const fullScreenHandle = useCallback(() => {
Еще момент. Мне кажется тут нет особого смысла в useCallback, смысл есть когда ты функцию передаешь как пропс дочернему компоненту. Вот тут можно почитать https://habr.com/ru/post/529950/.

2021-03-25 08:37 UTC, webtreegroup commented on client/core/components/GameCanvas/GameCanvas.tsx
> +    return <canvas ref={canvasRef} {...restProps} onDoubleClick={fullScreenHandle} />;
Вот сюда бы инфу добавить про двойной клик по канвасу
![image](https://user-images.githubusercontent.com/18382093/112443684-ad621900-8d66-11eb-8888-8c39b29de28d.png)

2021-03-25 12:34 UTC, webtreegroup approved these changes

2021-03-25 16:32 UTC, spt30 requested changes

2021-03-25 16:32 UTC, spt30 commented on client/core/components/GameCanvas/GameCanvas.tsx
> +    ...restProps
из ПРа лучше вычистить все, что не имеет к настоящим изменениям никакого отношения
в данном случае это какие-то непонятно зачем сделаные изменения, которые запутывают при чтении

если хочется поменять стиль написания — лучше прикрутить соответствующий линтер или форматтер и в отдельном ПРе сделать изменение стиля написания

2021-03-25 16:33 UTC, spt30 commented on client/core/components/GameCanvas/GameCanvas.tsx
> +    ...restProps
сюда же относится

![Снимок экрана 2021-03-25 в 21 32 57](https://user-images.githubusercontent.com/31798669/112508784-ad3b3b00-8db1-11eb-9582-60e23b41d5a1.png)

2021-03-25 16:33 UTC, spt30 commented
По логике все ок, кстати 👍  

Но надо прибраться

2021-03-26 15:54 UTC, spt30 approved these changes

2021-03-27 11:19 UTC, merged