Lp 15
LastPracticant/ya-practicum-m2 pull request #57
Opened 2021-02-21 12:16 UTC by webtreegroup

2021-02-21 14:12 UTC, Marat5 approved these changes

2021-02-22 13:19 UTC, spt30 requested changes
Критически важные комменты про именование переменной styles и про использование .toString()

2021-02-22 13:19 UTC, spt30 commented on client/core/components/Navigation/Navigation.tsx
> +const styles = block('navigation');
давай его называть `b` или как-то по другому, чтобы ссылаться именно на БЭМ, а не на стили
название класса ведь может пригодиться и не в стилях

2021-02-22 13:19 UTC, spt30 commented on client/core/components/PageLayout/PageLayout.tsx
> +                <Paper className={styles('aside').toString()}>
вроде должно работать так `styles('aside')()`

2021-02-22 13:19 UTC, spt30 commented on client/shared/components/Loader/Loader.tsx
> +            ).mix(className)}
годно, но мне кажется крисвше будет в одну строчку написать

2021-02-22 17:28 UTC, merged