Lp-44
LastPracticant/ya-practicum-m2 pull request #78
Opened 2021-03-03 16:07 UTC by AirMust

2021-03-03 21:16 UTC, webtreegroup commented on client/core/store/reducers/profile.reducers.ts
> +const initialStateProfile: CurrentUserInfoProps = {
тут можно просто пустой объект с приведением типа: {} as CurrentUserInfoProps

2021-03-03 21:16 UTC, webtreegroup commented on client/core/store/reducers/profile.reducers.ts
> +const getInitStateProfile = () => {
нет нужды хранить инфу о юзере в localStorage, лучше ее перезапрашивать каждый раз, тогда она будет всегда актуальной

2021-03-03 21:16 UTC, webtreegroup commented on client/core/store/reducers/profile.reducers.ts
> +const getInitStateProfile = () => {
функцию эту можно удалить

2021-03-03 21:16 UTC, webtreegroup commented on client/core/store/store.ts
> +const saveToLocalStorage = (state: StoreProps) => {
в данной функции нет необходимости, к тому же ей в данном файле точно не место

2021-03-03 21:16 UTC, webtreegroup commented on client/core/store/store.ts
> +store.subscribe(() => saveToLocalStorage(store.getState()));
лучше не делать подобные манипуляции, как то не по flow

2021-03-03 21:16 UTC, webtreegroup commented on client/pages/Forum/Forum.tsx
> +export const Forum = HOKAuth(ForumComponent);
по поводу наименования хоков выше писал,  это также относится и к директории, где хоки расположены

2021-03-03 21:16 UTC, webtreegroup commented on client/pages/Profile/Profile.tsx
> +    }
все это можно заменить на это
```
   const isProfile = useRouteMatch({ path: ROUTES.PROFILE.path, strict: true });

    const goBackLink = isProfile?.isExact
        ? ROUTES.HOME.path
        : ROUTES.PROFILE.path;
```
а вообще не парься и пускай у тебя ссылка ведет на home

2021-03-04 08:09 UTC, webtreegroup commented on client/core/components/PageLayout/PageLayout.css
> +        /* background-color: #212121; */
вот это нужно будет удалить

2021-03-04 08:11 UTC, webtreegroup approved these changes

2021-03-04 18:24 UTC, spt30 requested changes

2021-03-04 18:24 UTC, spt30 commented on client/core/HOCs/withCheckAuth.tsx
> +        }
`isSignin` и `isSignup` можно объединить здесь, даже нужно
типа вынести роуты в массив: `const signRoutes = [ROUTES.SIGNIN.path, ROUTES.SIGNUP.path];`
потом проверить что сейчас страница залогина `const isSignPageThere = signRoutes.some(useRouteMatch);`
затем вызывать это внутри условий: `!isAuth && !isSignPageThere`, `isAuth && isSignPageThere`

это будет годно с точки зрения SRP, так как оба условия здесь говорят только про то, находится ли пользователь на странице, с которой нужно/не нужно уходить

2021-03-04 18:24 UTC, spt30 commented on client/core/store/actions/auth.actions.ts
> +}
значение в localStorage можно поменять руками, поэтому checkAuth можно хакнуть в 2 клика

нужно присылать авторизационную куку и имя пользователя, хранить их локально и ходить в API с этой кукой и именем пользователя

за вас апи уже реализовано, поэтому надо просто ходить в него с клиента и получать информацию о пользователе, а только после этого решать, есть авторизация или нет

2021-03-04 18:24 UTC, spt30 commented on client/core/store/actions/auth.actions.ts
> +}
конечно, если в Redux уже приходила информация о пользователе и уже хранится там, то при переходе на другую страницу не надо снова запрашивать и ждать — можно сразу сказать, что пользователь авторизован

2021-03-04 18:24 UTC, spt30 commented on client/pages/Profile/components/ProfileEdit/ProfileEdit.tsx
> +    }, []);
зависимости у хука указаны неверно

2021-03-04 18:24 UTC, spt30 commented on client/pages/Profile/components/ProfileForm/ProfileForm.tsx
> +    }, []);
тут тоже

2021-03-06 07:48 UTC, webtreegroup approved these changes

2021-03-06 07:48 UTC, webtreegroup commented on client/core/store/store.types.ts
> +    auth: boolean | null,
->
```
auth: boolean
```

2021-03-06 07:48 UTC, webtreegroup commented on client/core/store/reducers/auth.reducers.ts
> +const initialState: boolean | null = null;
->
```
const initialState: boolean = false;
```

2021-03-06 07:48 UTC, webtreegroup commented on client/core/HOCs/withCheckAuth.tsx
> +            if (isAuth === null) {
->
```
if (!isAuth) {
```

2021-03-06 10:01 UTC, merged

2021-03-06 12:14 UTC, spt30 reviewed
ок