LP-86: Настроить middleware в Express для проверки авторизации пользователя до выдачи страницы и положить в хранилище на сервере. Настроить префетч данных.
LastPracticant/ya-practicum-m2 pull request #97
Opened 2021-03-16 17:43 UTC by webtreegroup

+ реализовал базовый механизм для BFF, завернул запросы с клиента на сервер Express

2021-03-18 07:53 UTC, Marat5 approved these changes

2021-03-20 16:42 UTC, spt30 requested changes

2021-03-21 17:15 UTC, spt30 commented on server/start.ts
> +const globals = global as any;
Такое решение не является best practice — придется каждый раз рыть код и смотреть, что же за зверь такой `globals`

Лучше всего будет [расширить](https://stackoverflow.com/questions/35074713/extending-typescript-global-object-in-node-js) global c помощью d.ts файла

Или **_в крайнем случае_** написать (global as any).FormData = FormData;

2021-03-21 17:15 UTC, spt30 commented on server/server.utils.ts
> +}
вместо composeCookie можно использовать просто `req.headers.cookie`

правильную и безопасный парсер кук можно легко нагуглить https://www.npmjs.com/package/set-cookie-parser
там же есть пример с тем, как их выставлять https://github.com/nfriedly/set-cookie-parser#creating-a-new-modified-set-cookie-header

2021-03-22 06:30 UTC, webtreegroup commented on server/server.utils.ts
> +}
поправил

2021-03-22 11:03 UTC, spt30 approved these changes

2021-03-22 11:09 UTC, merged